### PR TITLE
Api 22

### PR DESCRIPTION
**Pull request by kwonye**
Unit testing with gradle just simply isn't ready. There are a few hacks but instead of messying up the gradle file, I'd rather just split the work up and wait for it to be ready.

### CODE REVIEW

**Comment by tonyr59h** [comment]
Tested the sample app and verified code coverage reports. :+1:

Thanks for contributing! Hopefully Robolectric will be more readily supported soon.

**Comment by tonyr59h** [comment]
Spoke too soon! Can you merge in develop when you get a chance?

**Comment by kwonye** [comment]
Merged and all ready to go! @tonyr59h

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
